services:
  api:
    image: golang_gin_api:latest
    volumes:
      - "./api:/api"
    ports:
      - "8080:8080"
    depends_on:
      - db
#   fe:
#     build: 
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/frontend
#     command: sh -c "npm run dev"
#     stdin_open: true
  db:
    image: postgres:14.6
    restart: always
    ports:
      - 5433:${PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./sql/migrations:/docker-entrypoint-initdb.d
volumes:
  db-data: